### ISSUE TITLE
Check for algorithm of the results from candidates.

### ISSUE THREAD

**Issue by dafinaolluri** [crtarsorg/glasomer.rs-v2#34]
**Description**

We have answered all the questions on the same way as some candidate and didn’t get 100% matching (it was 91 or 95 percent). I don’t know how the algorithm works but want to check with you if that is OK. I was expecting that if I have all questions answered on the same way, my result should match 100 %.

**Comment by ferideadili** [comment]
@dafinaolluri  Tested it locally, if I answered all the questions exactly as one from candidates that I got 100%. 
One of the tests that I made is, if I assign answers to candidates, and than any of the questions I deleted after assigning the answers. 

The algorithm is to match the answers is:

- For every question, it checks first the answer of candidate than the answer of user. In this case found an answer that is not matching with the users answer, since the answer for candidate is given and the question was removed. The user is not answering to that question, and thats why we dont have 100% matchings. 

The solution is:

I edited the answers for the Aleksandar Popović, all the answers I assigned to him were: Slažem se , Nije važno

I voted as a user with same answers that I assigned to him and I am getting 100% matching with him.
