### ISSUE TITLE
Update Facebook share text and include photo every time we share on Facebook

### ISSUE THREAD

**Issue by georgeslabreche** [crtarsorg/glasomer.rs-v2#41]
The text should be:
_"Zanima te koliko se tvoji stavovi poklapaju sa stavovima predsedničkih kandidata? Proveri na Glasomeru.
Glasomer pomaže građanima da uporede svoje političke stavove sa stavovima kandidata koji se takmiče na predstojećim predsedničkim izborima. Izabrani stavovi su u vezi sa aktuelnim društveno-političkim dešavanjima u Srbiji."_

The image should be:
![glasomer-fb-img](https://cloud.githubusercontent.com/assets/1258236/24322184/057d76be-1167-11e7-846f-7d2c08de33ff.png)

**Comment by georgeslabreche** [comment]
@dafinaolluri @ferideadili not accepted because there is no distinction between title and description. All of it has been set as the title.

**The title should be:** _"Zanima te koliko se tvoji stavovi poklapaju sa stavovima predsedničkih kandidata? Proveri na Glasomeru."_

**And the description should be:** _"Glasomer pomaže građanima da uporede svoje političke stavove sa stavovima kandidata koji se takmiče na predstojećim predsedničkim izborima. Izabrani stavovi su u vezi sa aktuelnim društveno-političkim dešavanjima u Srbiji."_

**Comment by artaabdullahu** [comment]
I can not accepted because on Firefox when I am sharing with Facebook this description: "Glasomer pomaže građanima da uporede svoje političke stavove sa stavovima kandidata koji se takmiče na predstojećim predsedničkim izborima. Izabrani stavovi su u vezi sa aktuelnim društveno-političkim dešavanjima u Srbiji." is not displaying.
![screenshot from 2017-03-27 09 22 49](https://cloud.githubusercontent.com/assets/21961919/24347197/c487a144-12d7-11e7-8d55-e08b1bd611f3.png)
